package com.smartly.banking.mobilebff;
import static com.github.tomakehurst.wiremock.client.WireMock.*;
import static com.github.tomakehurst.wiremock.core.WireMockConfiguration.wireMockConfig;
import com.github.tomakehurst.wiremock.WireMockServer;
import java.time.Duration;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.test.web.reactive.server.WebTestClient;
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT,properties={"mobile-bff.authentication.demo-mode=true","mobile-bff.orchestrator.read-timeout=120ms","mobile-bff.orchestrator.connect-timeout=100ms","mobile-bff.orchestrator.retry-attempts=2"})
class MobileChatIntegrationTest{
 static final WireMockServer wiremock=new WireMockServer(wireMockConfig().dynamicPort());static{wiremock.start();}
 @DynamicPropertySource static void properties(DynamicPropertyRegistry registry){registry.add("mobile-bff.orchestrator.base-url",wiremock::baseUrl);}
 @LocalServerPort int port;WebTestClient client;
 @BeforeEach void setup(){wiremock.resetAll();client=WebTestClient.bindToServer().baseUrl("http://localhost:"+port).responseTimeout(Duration.ofSeconds(3)).build();}
 @AfterAll static void stop(){wiremock.stop();}
 private String request(){return "{\"customer_id\":\"C1024\",\"message\":\"Quel est mon solde ?\",\"conversation_id\":\"conv-1\",\"locale\":\"fr-FR\"}";}
 private String response(){return "{\"answer\":\"Votre solde est disponible.\",\"source\":\"get_account_balance\",\"sources\":[{\"type\":\"TOOL\",\"source\":\"account.balance.read\",\"data\":{\"available_balance\":\"100.00\",\"stack_trace\":\"secret\"},\"metadata\":{\"base_url\":\"http://internal-agent:8080\",\"agent_id\":\"account-agent\"}}],\"conversation_id\":\"conv-1\",\"request_id\":\"req-1\",\"internal_debug\":\"hidden\"}";}
 @Test void successfulChatOnBothRoutesAndSafeMapping(){wiremock.stubFor(post(urlEqualTo("/api/v1/chat")).willReturn(okJson(response())));for(String path:new String[]{"/chat","/api/mobile/v1/chat"})client.post().uri(path).header("Content-Type","application/json").bodyValue(request()).exchange().expectStatus().isOk().expectBody().jsonPath("$.answer").isEqualTo("Votre solde est disponible.").jsonPath("$.source").isEqualTo("get_account_balance").jsonPath("$.sources[0].data.stack_trace").doesNotExist().jsonPath("$.sources[0].metadata.base_url").doesNotExist().jsonPath("$.internal_debug").doesNotExist();}
 @Test void validationErrorIsSafe(){client.post().uri("/chat").header("Content-Type","application/json").bodyValue("{\"customer_id\":\"\",\"message\":\"\",\"locale\":\"bad\"}").exchange().expectStatus().isBadRequest().expectBody().jsonPath("$.code").isEqualTo("INVALID_REQUEST").jsonPath("$.message").isEqualTo("Request validation failed").jsonPath("$.stack_trace").doesNotExist();}
 @Test void timeoutIsMappedAndRetriedBoundedly(){wiremock.stubFor(post(urlEqualTo("/api/v1/chat")).willReturn(aResponse().withFixedDelay(400).withStatus(200).withBody(response()).withHeader("Content-Type","application/json")));client.post().uri("/chat").header("Content-Type","application/json").bodyValue(request()).exchange().expectStatus().isEqualTo(504).expectBody().jsonPath("$.code").isEqualTo("ORCHESTRATOR_TIMEOUT").jsonPath("$.retryable").isEqualTo(true);wiremock.verify(2,postRequestedFor(urlEqualTo("/api/v1/chat")));}
 @Test void orchestrator500IsMappedWithoutLeak(){wiremock.stubFor(post(urlEqualTo("/api/v1/chat")).willReturn(serverError().withBody("java.lang.IllegalStateException: secret")));client.post().uri("/chat").header("Content-Type","application/json").bodyValue(request()).exchange().expectStatus().isEqualTo(502).expectBody().jsonPath("$.code").isEqualTo("ORCHESTRATOR_ERROR").jsonPath("$.message").isEqualTo("The assistant is temporarily unavailable").jsonPath("$.stack_trace").doesNotExist();wiremock.verify(2,postRequestedFor(urlEqualTo("/api/v1/chat")));}
 @Test void propagatesRequestAuthenticationAndApprovedMobileContext(){wiremock.stubFor(post(urlEqualTo("/api/v1/chat")).willReturn(okJson(response())));client.post().uri("/chat").header("Content-Type","application/json").header("X-Request-Id","req-mobile").header("X-Correlation-Id","corr-mobile").header("traceparent","00-0123456789abcdef0123456789abcdef-0123456789abcdef-01").header("X-Demo-Subject-Id","mobile-user-7").header("X-Demo-Customer-Id","C1024").header("X-App-Version","2.4.1").header("X-Device-Class","PHONE").header("User-Agent","Sensitive Device Serial 123").bodyValue(request()).exchange().expectStatus().isOk().expectHeader().valueEquals("X-Request-Id","req-mobile").expectHeader().valueEquals("X-Correlation-Id","corr-mobile");wiremock.verify(postRequestedFor(urlEqualTo("/api/v1/chat")).withHeader("X-Request-Id",equalTo("req-mobile")).withHeader("X-Correlation-Id",equalTo("corr-mobile")).withHeader("X-Conversation-Id",equalTo("conv-1")).withHeader("X-Authenticated-Subject-Id",equalTo("mobile-user-7")).withHeader("X-Authenticated-Customer-Id",equalTo("C1024")).withHeader("X-Channel",equalTo("MOBILE")).withHeader("X-App-Version",equalTo("2.4.1")).withHeader("X-Device-Class",equalTo("PHONE")).withHeader("traceparent",equalTo("00-0123456789abcdef0123456789abcdef-0123456789abcdef-01")).withHeader("User-Agent",notMatching(".*Sensitive Device Serial.*")).withRequestBody(notMatching(".*app_version.*|.*device_class.*")));}
 @Test void crossCustomerDemoContextIsNotDisclosed(){client.post().uri("/chat").header("Content-Type","application/json").header("X-Demo-Customer-Id","C2048").bodyValue(request()).exchange().expectStatus().isNotFound().expectBody().jsonPath("$.code").isEqualTo("CUSTOMER_CONTEXT_NOT_FOUND");wiremock.verify(0,postRequestedFor(anyUrl()));}
}
