from typing import Any,Protocol
from orchestrator.models import AgentResult,AnswerDraft,ChatRequest,Decision,Evidence,Principal,RagResult,Resolution,RoutingPlan
class RouterPort(Protocol):
    async def route(self,request:ChatRequest)->RoutingPlan:...
class AnswerPort(Protocol):
    async def answer(self,request:ChatRequest,evidence:list[Evidence],safe_instruction:str)->AnswerDraft:...
class DirectAnswerPort(Protocol):
    async def answer(self,request:ChatRequest)->AnswerDraft:...
class RegistryPort(Protocol):
    async def resolve(self,capability:str,headers:dict[str,str])->Resolution:...
    async def health(self)->bool:...
class PolicyPort(Protocol):
    async def authorize(self,principal:Principal,capability:str,customer_id:str|None,resource:dict[str,Any],headers:dict[str,str])->Decision:...
    async def health(self)->bool:...
class AgentPort(Protocol):
    async def execute(self,resolution:Resolution,payload:dict[str,Any],headers:dict[str,str],retry:bool=True)->AgentResult:...
class KnowledgePort(Protocol):
    async def search(self,resolution:Resolution,query:str,locale:str,filters:dict[str,Any],headers:dict[str,str])->list[RagResult]:...
class AuditPublisher(Protocol):
    async def publish(self,event_type:str,payload:dict[str,Any],context:dict[str,str])->None:...
class ConversationStore(Protocol):
    async def touch(self,conversation_id:str,locale:str)->None:...
